package com.solumesl.aims.saas.adapter.entity.job;

public enum JobStatus {
	PRE_ACCEPT,ACCEPTED,PROCESSING,COMPLETED,STOPPED,ERROR, MASTER_COMPLETE, MASTER_ERROR, CHILD_PRE_ACCEPT, CHILD_ACCEPTED, CHILD_PROECESSING, CHILD_COMPLETE, CHILD_ERROR, MASTER_PROCESSING, MASTER_PARTIAL_COMPLETE
}
